### ISSUE TITLE
Error displayed on .connect token.

### ISSUE THREAD

**Issue by dgovil** [justint/usd-idea#1]
Here's a sample usda (nothing functional, just a stripped back example) using the 0.2.2 version of the plugin.

The first connection shows an error saying it expects it to be named alpha instead of connect.
`.connect` however is valid. This error also stops on the first instance, but not any others.

```
#usda 1.0

def "Foo"
{
    def "MyShader"
    {
        token outputa.connect = </path>
        token outputb.connect = </path>
    }
}
```

![image](https://user-images.githubusercontent.com/4443090/59972804-81d74c80-954a-11e9-9993-a796550d2bf7.png)

Also great work!

**Comment by justint** [comment]
Hey @dgovil, thanks for alerting me about this! 

I've been on a hiatus while wrapping up on a show, I now have more time to work on this project. I'll push out a commit tonight to fix this issue and version 0.2.3 will have it included.
