### ISSUE TITLE
new build for Marketplace with 2021 support?

### ISSUE THREAD

**Issue by YKdvd** [justint/usd-idea#19]
There are recent commits that seem to indicate support for the 2021.1+ JetBrain IDEs, but a new build hasn't been made for the Marketplace.  Is this support ready to go and buildable, or is more work needed?  I like to use this in my PyCharm 2021.1.1 setup.

**Comment by justint** [comment]
Hey, thanks for checking in about this! It slipped my mind to get a 2021.1 + 2021.2 build up on the Marketplace.

I've just released [v0.4.1](https://github.com/justint/usd-idea/releases/tag/v0.4.1) and uploaded that build to the Marketplace, it should be available as an update in PyCharm within two business days. I'll close this out once the update is live.

**Comment by justint** [comment]
v0.4.1 is now live on the Marketplace: https://plugins.jetbrains.com/plugin/12407-usd/versions/stable/131700
